import React,{useEffect,useRef,useState} from 'react';
import {Editor} from '../Editor.jsx';
import {PythonRuntime,friendlyError} from '../runtime.js';
import {downloadFile} from '../storage.js';
import {recordAttempt,taskStatus} from '../evidence.js';
import {LearningReview} from '../LearningReview.jsx';
import {ReportPanel} from '../ReportPanel.jsx';
import {Walkthrough,stepDescription} from '../week2/Walkthrough.jsx';
import {stages,main1,main2,extensions,levels,tasks,taskById,sources,plenary,warmups,checkSpec} from './content.js';
import {topics,reviewAt,updateReview,reportConfig,validateWeek3,answerResult,progress} from './state.js';
import './week3.css';

function Grid({rows}){
 const [selected,setSelected]=useState(0);
 return <div className="mcc-grid-wrap"><p className="mcc-small">Select a column. Dots are gaps; hashes are existing fences.</p><div className="mcc-grid" style={{gridTemplateColumns:`repeat(${rows[0].length}, minmax(34px,48px))`}} role="group" aria-label="Field columns">{rows[0].split('').map((_,c)=><button key={'col'+c} className="mcc-column" aria-pressed={selected===c} onClick={()=>setSelected(c)} aria-label={`Select column ${c+1}`}>{c+1}</button>)}{rows.flatMap((row,r)=>row.split('').map((cell,c)=><button key={r+'-'+c} className={'mcc-cell '+(selected===c?'selected':'')} onClick={()=>setSelected(c)} aria-label={`Row ${r+1}, column ${c+1}: ${cell==='.'?'gap':'fence'}`}><span aria-hidden="true">{cell}</span></button>))}</div><p className="mcc-small" aria-live="polite">Column {selected+1} selected. Count its dots from top to bottom.</p></div>;
}
function CodeText({children}){return <pre className="mcc-code-text"><code>{children}</code></pre>;}
export function Week3App({profile,initialWork,onSave,onLeave}){
 const [work,setWork]=useState(()=>({...initialWork,drafts:initialWork.drafts||{}}));
 const [page,setPage]=useState('lesson');
 const [stageId,setStageId]=useState(stages.some(s=>s.id===initialWork.stage)?initialWork.stage:'ready');
 const [taskId,setTaskId]=useState(taskById(initialWork.task)?initialWork.task:'a1');
 const [example,setExample]=useState(false),[status,setStatus]=useState('loading'),[output,setOutput]=useState(''),[feedback,setFeedback]=useState(null),[error,setError]=useState('');
 const [saved,setSaved]=useState(true),[notice,setNotice]=useState(''),[fontSize,setFontSize]=useState(18),[textSize,setTextSize]=useState(19),[showPython,setShowPython]=useState(false);
 const [trace,setTrace]=useState(null),[position,setPosition]=useState(0),[paused,setPaused]=useState(false);
 const runtime=useRef(),editor=useRef(),active=useRef(),latest=useRef(),importRef=useRef(),inputRef=useRef();
 const busy=['running','checking','tracing'].includes(status);
 const stageIndex=stages.findIndex(s=>s.id===stageId),stage=stages[stageIndex];
 const task=stageId==='donow'?warmups[0]:stageId==='condition'?warmups[1]:stageId==='plenary'?plenary:taskById(taskId)||main1[0];
 const isPractice=['main1','main2','donow','condition','plenary'].includes(stageId);
 const draft=example?(work.exampleDrafts?.[task.id]??task.example):(work.drafts?.[task.id]??task.starter);
 const stdin=example?(work.exampleInputs?.[task.id]??task.exampleInput??''):(work.inputs?.[task.id]??task.sampleInput??'');
 const current=useRef();current.current={task,draft,stdin,example};
 latest.current={...work,stage:stageId,task:taskId};
 useEffect(()=>{const timer=setTimeout(()=>setSaved(onSave(latest.current)),250);return()=>clearTimeout(timer);},[work,stageId,taskId]);
 useEffect(()=>{const save=()=>onSave(latest.current);window.addEventListener('pagehide',save);return()=>{save();window.removeEventListener('pagehide',save);};},[]);
 useEffect(()=>{
  runtime.current=new PythonRuntime({
   status:(s,message)=>{setStatus(s);if(message)setError(message);},
   output:text=>{setOutput(old=>old+text);if(active.current)active.current.output+=text;},
   input:()=>setError('This exercise uses the input box above. Stop, add all input lines and run again.'),
   stopping:message=>setNotice(message),
   trace:(step,isPaused)=>{setTrace(old=>{const next={...old,steps:[...(old?.steps||[]),step]};setPosition(next.steps.length-1);return next;});setPaused(isPaused);},
   finish:result=>{
    const attempt=active.current;
    if(attempt&&!attempt.example&&attempt.kind!=='trace')setWork(old=>recordAttempt(old,attempt,result));
    if(result.type==='checked'){
     setFeedback(result.result);
     if(result.result.passed&&attempt)setWork(old=>({...old,passed:{...old.passed,[attempt.taskId]:attempt.code}}));
    }
    if(result.type==='error'){setError(result.stopped?'Program stopped. Your work is kept.':result.message);if(attempt?.kind==='trace')setTrace(old=>({...old,error:result.message}));}
    setPaused(false);active.current=null;
   },
  });runtime.current.start();return()=>runtime.current.destroy();
 },[]);
 function clear(){setExample(false);setOutput('');setFeedback(null);setError('');setTrace(null);setShowPython(false);}
 function guard(){if(runtime.current?.active){setNotice('Stop the program before changing pages.');return false;}return true;}
 function openStage(id){if(!guard())return;setStageId(id);if(id==='main1')setTaskId(main1[0].id);if(id==='main2')setTaskId(main2[0].id);setPage('lesson');clear();setNotice('');window.scrollTo({top:0});}
 function openTask(id){const t=taskById(id);if(!t){if(stages.some(s=>s.id===id))openStage(id);return;}if(!guard())return;setTaskId(id);setStageId(t.level?'main2':t.group);setPage('lesson');clear();setWork(old=>({...old,visited:{...old.visited,[id]:true}}));window.scrollTo({top:0});}
 function openPage(value){if(!guard())return;setPage(value);setNotice('');}
 function updateField(field,value){setWork(old=>({...old,[field]:{...old[field],[task.id]:value}}));}
 function changeCode(value){if(busy)return;updateField(example?'exampleDrafts':'drafts',value);setFeedback(null);setTrace(null);}
 function run(kind='run'){
  if(runtime.current?.active||!runtime.current?.ready)return;
  const c=current.current;
  setOutput('');setFeedback(null);setError('');setTrace(null);setPosition(0);
  active.current={taskId:c.task.id,code:c.draft,inputs:c.stdin?[c.stdin]:[],output:'',kind,example:c.example,startedAt:new Date().toISOString()};
  if(!c.example)setWork(old=>({...old,attempted:{...old.attempted,[c.task.id]:true}}));
  if(kind==='trace'){setTrace({code:c.draft,example:c.example,steps:[]});runtime.current.walk(c.draft,{stdin:c.stdin});}
  else runtime.current.execute(c.draft,kind==='check'?c.task.check:undefined,{stdin:c.stdin,spec:checkSpec(c.task)});
 }
 function checkAnswer(){const value=work.answers?.[task.id]||'',result=answerResult(task,value);setFeedback(result);setWork(old=>{const next=recordAttempt(old,{taskId:task.id,code:value,inputs:[task.sampleInput],output:value,kind:'check',startedAt:new Date().toISOString()},{type:'checked',result});return {...next,attempted:{...next.attempted,[task.id]:true},passed:result.passed?{...next.passed,[task.id]:value}:next.passed};});}
 function next(){if(isPractice&&task.level){openPage('extensions');return;}const group=stageId==='main1'?main1:stageId==='main2'?main2:null;const index=group?.findIndex(t=>t.id===task.id);if(group&&index>=0&&index<group.length-1)openTask(group[index+1].id);else if(stageIndex<9)openStage(stages[stageIndex+1].id);else openPage('report');}
 function back(){const group=stageId==='main1'?main1:stageId==='main2'?main2:null;const index=group?.findIndex(t=>t.id===task.id);if(isPractice&&task.level)openPage('extensions');else if(group&&index>0)openTask(group[index-1].id);else if(stageIndex>0)openStage(stages[stageIndex-1].id);}
 function backup(){downloadFile('kl-coding-week-3-backup.json',JSON.stringify({format:'kl-coding-lab-backup',version:3,lesson:3,student:{name:profile.name,className:profile.className},work:latest.current},null,2),'application/json');}
 async function restore(e){const file=e.target.files?.[0];if(!file)return;try{if(file.size>5000000)throw Error('Choose a backup smaller than 5 MB.');const data=JSON.parse(await file.text());if(data.format!=='kl-coding-lab-backup'||data.lesson!==3)throw Error('Choose a Week 3 backup. Other weeks have their own backups.');const cleaned=validateWeek3(data.work);backup();setWork(cleaned);setStageId(cleaned.stage);setTaskId(cleaned.task);clear();setNotice('Backup restored. Your previous work was downloaded first.');}catch(err){setNotice(err.message);}e.target.value='';}
 async function loadInput(e){const file=e.target.files?.[0];if(!file)return;try{if(file.size>100000)throw Error('Choose an input file smaller than 100 KB for this lesson.');updateField(example?'exampleInputs':'inputs',await file.text());}catch(err){setNotice(err.message);}e.target.value='';}
 function nextTrace(iteration){if(position<trace.steps.length-1){const nextIndex=iteration?trace.steps.findIndex((s,i)=>i>position&&(s.iterationChanged||s.loopFinished||s.event==='end')):position+1;setPosition(nextIndex<0?trace.steps.length-1:nextIndex);}else if(runtime.current.nextTrace(iteration))setPaused(false);}
 const group=stageId==='main1'?main1:stageId==='main2'&&!task.level?main2:null;
 const navButtons=<div className="mcc-bottom"><button disabled={busy||stageIndex===0} onClick={back}>← Back</button><button className="mcc-primary" disabled={busy} onClick={next}>{isPractice&&task.level?'All extensions':stageIndex===9?'My learning report':group&&group.at(-1).id!==task.id?'Next practice →':'Continue →'}</button></div>;
 function feedbackPanel(){return feedback&&<section className="mcc-feedback" aria-live="polite"><h3>{feedback.passed?'✓ This check passed':'Let’s investigate'}</h3><p>{feedback.message}</p>{feedback.error&&<CodeText>{feedback.error}</CodeText>}{feedback.cases?.map((c,i)=><details key={i}><summary>Test {i+1} · {c.passed?'Passed':'Needs another look'} · reveal details</summary><div className="mcc-samples"><div><b>Input</b><CodeText>{c.input||'Data in the starter'}</CodeText></div><div><b>Expected output</b><CodeText>{c.expected}</CodeText></div></div><b>Your output</b><CodeText>{c.actual||'(nothing printed)'}</CodeText>{c.error&&<CodeText>{c.error}</CodeText>}</details>)}</section>;}
 const pythonWorkspace=<section className="mcc-python" aria-label="Built-in Python workspace">
  {example&&<div className="mcc-example-banner"><b>Exploring the example</b><p>Your own program stays separate.</p><button disabled={busy} onClick={()=>{setExample(false);setTrace(null);setOutput('');setError('');}}>Back to my code</button></div>}
  <div className="mcc-editor-label"><b>{example?'Example sandbox':'Your Python code'}</b><span role="status">{({loading:'Loading Python…',ready:'Python ready',running:'Running…',checking:'Checking fresh inputs…',tracing:'Walking through',unavailable:'Python needs attention'})[status]}</span></div>
  <div className="mcc-editor"><Editor ref={editor} key={task.id+(example?'-example':'')} value={draft||''} onChange={changeCode} onRun={()=>run()} fontSize={fontSize} readOnly={busy} executedLine={trace?.steps[position]?.executedLine} nextLine={trace?.steps[position]?.nextLine}/></div>
  <div className="mcc-runbar"><button className="mcc-primary" disabled={status!=='ready'} onClick={()=>run()}>Run</button>{!example&&task.kind!=='output'&&task.tests?.length>0&&<button disabled={status!=='ready'} onClick={()=>run('check')}>Check my code</button>}{busy&&<button className="mcc-stop" onClick={()=>runtime.current.stop()}>Stop</button>}<span className="mcc-small">Ctrl / ⌘ + Enter to run</span></div>
  <details className="mcc-tools"><summary>Editor tools & walkthrough</summary><div className="mcc-tool-buttons"><button disabled={busy||status!=='ready'} onClick={()=>run('trace')}>Walk through</button><button disabled={busy} onClick={()=>editor.current?.indent()}>Indent</button><button disabled={busy} onClick={()=>editor.current?.outdent()}>Outdent</button><button disabled={busy} onClick={()=>editor.current?.undo()}>Undo</button><button onClick={()=>setFontSize(s=>s===22?16:s+2)}>Code text size</button><button onClick={()=>downloadFile(`week3-${task.id}${example?'-example':''}.py`,draft||'')}>Download Python</button><button disabled={busy} onClick={()=>{if(!example)updateField('recoverable',draft||'');changeCode(example?task.example:task.starter);setNotice('Starter restored. Recover previous draft is available below.');}}>Reset to starter</button>{!example&&work.recoverable?.[task.id]!==undefined&&<button disabled={busy} onClick={()=>changeCode(work.recoverable[task.id])}>Recover previous draft</button>}</div><p className="mcc-small">Tab indents. Escape, then Tab leaves the editor. Walkthroughs pause real execution and stop after 300 steps; use a small input.</p></details>
  <label className="mcc-input-label" htmlFor="mcc-input">Program input <span>One line per input() call</span></label><textarea id="mcc-input" rows={3} value={stdin} maxLength={100000} disabled={busy} onChange={e=>updateField(example?'exampleInputs':'inputs',e.target.value)} spellCheck={false} placeholder="No input needed when the data is already in your code."/>
  <div className="mcc-input-actions"><button disabled={busy} onClick={()=>inputRef.current.click()}>Load input file</button><button disabled={busy} onClick={()=>updateField(example?'exampleInputs':'inputs',example?task.exampleInput||'':task.sampleInput||'')}>Restore sample input</button></div>
  <div className="mcc-output"><b>Program output</b><pre aria-label="Program output">{output||'Your output will appear here.'}</pre></div>
  {error&&<div className="mcc-feedback" role="alert"><b>{friendlyError(error).tip}</b><details><summary>Read the Python message</summary><CodeText>{error}</CodeText></details></div>}
  {status==='unavailable'&&<button onClick={()=>globalThis.crossOriginIsolated?runtime.current.start():location.reload()}>Reload Python</button>}
  {trace&&<Walkthrough trace={trace} position={position} paused={paused} busy={status==='tracing'} waiting={false} onPosition={setPosition} onNext={nextTrace} onRestart={()=>run('trace')} onStop={()=>runtime.current.stop()} onClose={()=>setTrace(null)} onSave={step=>{updateField('traceEvidence',{code:trace.code,description:stepDescription(step,trace.example)});setNotice('Step saved. Add your own explanation below.');}}/>}
  {task.kind!=='output'&&feedbackPanel()}
  <p className="mcc-small">{task.dataName||task.variables?'Checks replace only the named starter data with fresh values. Keep those top-level data assignments.':'Run uses the input above. Checks use fresh inputs without changing your program.'} These are classroom practice checks, not an official MCC judge.</p>
 </section>;
 return <div className="mcc-app" style={{'--mcc-reading-size':textSize+'px'}}>
  <header className="mcc-header"><button className="mcc-brand" disabled={busy} onClick={()=>openPage('lesson')}>KL <b>Coding Lab</b></button><nav aria-label="Week 3 navigation">{['lesson','extensions','teacher'].map(p=><button key={p} aria-current={page===p?'page':undefined} disabled={busy} onClick={()=>openPage(p)}>{p==='teacher'?'Teacher guide':p[0].toUpperCase()+p.slice(1)}</button>)}</nav><button onClick={()=>setTextSize(v=>v===21?18:v+1)} aria-label="Change reading text size">Aa</button></header>
  <div className="mcc-student"><span><b>{profile.name}</b> · {profile.className} · Week 3</span><div><button disabled={busy} onClick={()=>openPage('files')}>My files</button><button disabled={busy} onClick={()=>openPage('report')}>My learning report</button><button disabled={busy} onClick={()=>{if(onSave(latest.current))onLeave();else setNotice('Download a backup before switching: saving is unavailable.');}}>Change week / student</button></div></div>
  {notice&&<div className="mcc-notice" role="status">{notice}<button onClick={()=>setNotice('')}>Dismiss</button></div>}
  <div className="mcc-title"><p className="mcc-eyebrow">WEEK 03 · MCC PREPARATION · 60 MINUTES</p><h1>From Problem to Submission</h1><p>Read a little. Try an idea. Build a solution you can explain.</p></div>
  <div className="mcc-shell">
   <aside className="mcc-sidebar"><details open><summary>Lesson map · {progress(work)}/8 core checks</summary><nav aria-label="Ten lesson stages">{stages.map((s,i)=><button key={s.id} disabled={busy} aria-current={page==='lesson'&&stageId===s.id?'step':undefined} onClick={()=>openStage(s.id)}><span>{i+1}</span><div><b>{s.label}</b><small>{s.time} min</small></div></button>)}</nav></details><p className="mcc-small">{saved?'Saved in this browser':'Saving unavailable — download a backup'}. Keep a backup before changing devices.</p></aside>
   <main className="mcc-main">
    {page==='extensions'&&<><p className="mcc-eyebrow">CHOOSE SUPPORT OR STRETCH</p><h2>Extensions</h2><p>Choose any level. You do not need to finish every question today. These are classroom adaptations of MCC past problems.</p>{levels.map(level=><section key={level} className="mcc-extension-group"><h3>{level} <span>{extensions.filter(t=>t.level===level).length} questions</span></h3><div className="mcc-extension-list">{extensions.filter(t=>t.level===level).map(t=><button key={t.id} onClick={()=>openTask(t.id)}><span><b>{t.title}</b><small>{sources[t.source].name}</small></span><span>{taskStatus(t,work)} →</span></button>)}</div></section>)}</>}
    {page==='files'&&<><h2>Keep your work</h2><p>These files belong to your Week 3 profile. Your Week 1 and Week 2 work stays separate.</p><div className="mcc-file-actions"><button className="mcc-primary" onClick={backup}>Download Week 3 backup</button><button onClick={()=>importRef.current.click()}>Restore Week 3 backup</button><button onClick={()=>openPage('report')}>Download learning report (PDF)</button></div><p>Before restoring a backup, your current work downloads automatically. The selected backup replaces this Week 3 lesson only.</p><h3>Answer files</h3>{[...main1,plenary].map(t=><div className="mcc-file-row" key={t.id}><span>{t.title}</span><button disabled={!work.answers?.[t.id]?.trim()} onClick={()=>downloadFile(`week3-${t.id}.txt`,(work.answers[t.id]||'').trim()+'\n')}>Download answer</button></div>)}</>}
    {page==='report'&&<ReportPanel profile={profile} work={work} setWork={setWork} busy={busy} onBackup={backup} lessonConfig={reportConfig}/>}
    {page==='teacher'&&<><p className="mcc-eyebrow">TEACHER REFERENCE · ANSWERS INSIDE</p><h2>Week 3 guide</h2><p><b>WAGBA:</b> Read a competition problem, develop a method and produce an answer in the required format.</p><p>Keep all ten stages. Main Task 1 has three questions; Main Task 2 has five. Extensions contain 2 Pre-Bronze, 4 Bronze, 3 Silver and 1 Gold. The bank supports choice and revisits; completing every question in one hour is not expected.</p><p>Conditions, indexing and nested loops may be new. Beginners prioritise B1–B2. Supply the parser and use small grids. Ask for a fresh individual explanation at the plenary.</p><p><a href="https://ioimalaysia.org/competition/mcc/info/" target="_blank" rel="noreferrer">MCC rules</a>: output files and code submissions are different. Classroom collaboration is preparation; the actual contest prohibits discussing problems and generative-AI assistance.</p><div className="mcc-table-scroll"><table><thead><tr><th>Minutes</th><th>Stage</th></tr></thead><tbody>{stages.map(s=><tr key={s.id}><td>{s.time}</td><td>{s.label}</td></tr>)}</tbody></table></div>{tasks.map(t=><details className="mcc-teacher-answer" key={t.id}><summary>{t.level?`${t.level} · `:''}{t.title}</summary><p>{t.teacher}</p>{t.answer!==undefined&&<p><b>Answer:</b> {t.answer}</p>}{t.solution&&<><h4>Reference Python</h4><CodeText>{t.solution}</CodeText><p>Ask the student to name what is initialised, what repeats, what condition chooses, and what is printed. Use Walk through with a small input to inspect actual line values.</p></>}{t.tests?.map((c,i)=><div key={i}><b>Test {i+1}</b><CodeText>{c.data!==undefined?JSON.stringify(c.data):c.input}</CodeText><p>Expected: {c.expected}</p></div>)}{t.source&&<a href={sources[t.source].url} target="_blank" rel="noreferrer">{sources[t.source].name}</a>}</details>)}<p className="mcc-small">Teacher reference is openly accessible, not password protected. Browser checks conceal data in the normal view only; they are not a secure assessment system.</p></>}
    {page==='lesson'&&<>
     <p className="mcc-eyebrow">STAGE {stageIndex+1} OF 10 · {stage.time} MIN · {stage.label}</p>
     {['focus','pitstop1','pitstop2'].includes(stageId)?<LearningReview key={stageId} topics={topics} after={stageId!=='focus'} checkpointLabel={stageId==='pitstop1'?'Learning Pit Stop 1':'Learning Pit Stop 2'} work={{learningReview:reviewAt(work,stageId)}} setWork={updater=>setWork(old=>updateReview(old,stageId,updater({learningReview:reviewAt(old,stageId)}).learningReview))} saved={saved} onOpen={openTask} onBack={back} onContinue={next}/>:stageId==='ready'?<>
      <h2>Your next competition step</h2><p className="mcc-lead">You have used lists, loops and counters. Today you will use them to solve a competition problem.</p><div className="mcc-learning-goal"><b>We are getting better at…</b><p>Reading a problem, choosing a method and producing the answer it asks for.</p></div><h3>A small step at a time</h3><p>Read the explanation. Explore an example. Try your own code. Check a new case and explain what happened.</p><p>You can use a hint, choose a smaller step or open Extensions at any time. In practice, a coder types while a checker suggests tests. Swap roles and each explain one step.</p><p>At the end, you will solve a fresh field and keep your own answer and explanation.</p>{navButtons}
     </>:stageId==='formats'?<>
      <h2>What are you submitting?</h2><p>A correct calculation is only useful when you submit the right thing. MCC uses two formats.</p><div className="mcc-format"><h3>Output format</h3><p>Read the supplied input file. Work out its answer, by hand or using code. Submit an output file containing that answer.</p><CodeText>{'input.txt → your method → answer.txt'}</CodeText></div><div className="mcc-format"><h3>Code format</h3><p>Submit a program. The judge runs it on inputs you have not seen. Your program reads standard input and prints the required output.</p><CodeText>{'new input → your program → output → check'}</CodeText></div><h3>Read the rule carefully</h3><p>For Building Fences, the output is the number of new pieces needed to complete one vertical column. A column number answers a different question.</p><p>For example, the fourth column might need only two pieces. You would submit <code>2</code>.</p><details><summary>Constraints and smaller tasks</summary><p>A constraint is an input limit. Small cases can be solved by hand; larger ones make automation useful. In code format, all tests in a scored subtask must pass. Our lesson checks are practice, not official points.</p></details><p className="mcc-small"><a href="https://ioimalaysia.org/competition/mcc/info/" target="_blank" rel="noreferrer">Official MCC information</a> · Keep any code used to produce output files for the exit survey.</p>{navButtons}
     </>:isPractice&&<>
      {task.level&&<button onClick={()=>openPage('extensions')}>← All extensions · {task.level}</button>}
      {group&&<section className="mcc-practice-bank" aria-label={`${stage.label} practice questions`}><h2>{stage.title}</h2><p>{group.length} practice questions. Pause when your teacher calls the pit stop; unfinished questions stay available.</p><nav aria-label="Choose a practice question">{group.map((t,i)=><button key={t.id} disabled={busy} aria-current={t.id===task.id?'step':undefined} onClick={()=>openTask(t.id)}><span>{i+1}</span><b>{t.title}</b></button>)}</nav><button className="mcc-link-button" disabled={busy} onClick={()=>openStage(stageId==='main1'?'pitstop1':'pitstop2')}>Go to learning pit stop →</button></section>}
      <article className="mcc-reading" key={task.id}>
       <p className="mcc-eyebrow">{task.level?task.level+' · EXTENSION':task.kind==='output'?'OUTPUT PRACTICE':'READ · TRY · EXPLAIN'}</p><h2>{task.title}</h2>
       {stageId==='plenary'?<p>Try this independently first. You may calculate by hand or use your own program. Explain what your answer represents and record any help you use.</p>:<><p className="mcc-lead">{task.learn}</p>{task.extraReading&&<details><summary>A smaller step: dictionaries</summary><p>{task.extraReading}</p></details>}<section className="mcc-worked"><h3>One small example</h3><CodeText>{task.example}</CodeText><div className="mcc-samples">{task.exampleInput&&<div><b>Example input</b><CodeText>{task.exampleInput}</CodeText></div>}<div><b>Sample output</b><CodeText>{task.exampleOutput}</CodeText></div></div>{task.exampleExplanation&&<p>{task.exampleExplanation}</p>}{task.kind!=='output'&&<><button disabled={busy} onClick={()=>{setExample(true);setTrace(null);setOutput('');setFeedback(null);setError('');}}>Explore this example in Python</button><p className="mcc-small">{task.tryChange||'Change one value in the example and run it again. Explain the change in output.'}</p></>}</section></>}
       <section className="mcc-your-turn"><p className="mcc-eyebrow">YOUR TURN</p><h3>{stageId==='plenary'?'Solve the fresh field':task.kind==='output'?'Make your answer file':'Build and test your solution'}</h3><p>{task.goal}</p>{task.kind!=='output'&&<div className="mcc-samples"><div><b>Sample input</b><CodeText>{task.sampleInput||'Use the data supplied in the starter.'}</CodeText></div><div><b>Expected output</b><CodeText>{task.sampleOutput}</CodeText></div></div>}
       {task.kind==='output'?<><CodeText>{task.sampleInput}</CodeText><Grid key={task.id} rows={task.grid}/><label htmlFor="mcc-answer">Your answer · one integer</label><input id="mcc-answer" value={work.answers?.[task.id]||''} maxLength={40} inputMode="numeric" onChange={e=>{updateField('answers',e.target.value);setFeedback(null);}}/><div className="mcc-runbar"><button className="mcc-primary" onClick={checkAnswer}>Check my answer</button><button disabled={!work.answers?.[task.id]?.trim()} onClick={()=>downloadFile(`week3-${task.id}.txt`,(work.answers[task.id]||'').trim()+'\n')}>Download answer file</button><button onClick={()=>downloadFile(`week3-${task.id}-input.txt`,task.sampleInput)}>Download input</button></div>{feedbackPanel()}<button className="mcc-link-button" disabled={busy} onClick={()=>setShowPython(v=>!v)}>{showPython?'Close Python workspace':'Use Python to work it out (optional)'}</button>{showPython&&pythonWorkspace}</>:pythonWorkspace}
       </section>
       {task.hints.length>0&&<div className="mcc-hints"><button disabled={(work.hints?.[task.id]||0)>=task.hints.length} onClick={()=>updateField('hints',(work.hints?.[task.id]||0)+1)}>Show a small hint ({Math.min(work.hints?.[task.id]||0,task.hints.length)}/{task.hints.length})</button>{task.hints.slice(0,work.hints?.[task.id]||0).map((hint,i)=><p key={i} style={{whiteSpace:'pre-wrap'}}><b>Hint {i+1}.</b> {hint}</p>)}</div>}
       <details className="mcc-explanation" open={stageId==='plenary'}><summary>Explain your work · saved in your report</summary><label htmlFor="mcc-explanation">What changed? What did your test show? Did you use a hint or help?</label><textarea id="mcc-explanation" rows={3} maxLength={3000} value={work.explanations?.[task.id]||''} onChange={e=>updateField('explanations',e.target.value)} placeholder="I tested… This showed… I used…"/></details>
       {task.source&&<p className="mcc-source">{task.relation} <a href={sources[task.source].url} target="_blank" rel="noreferrer">{sources[task.source].name}</a></p>}
       {navButtons}
      </article>
     </>}
    </>}
   </main>
  </div>
  <input hidden ref={importRef} type="file" accept=".json" onChange={restore}/><input hidden ref={inputRef} type="file" accept=".txt,.in" onChange={loadInput}/>
 </div>;
}
