// Short scenarios share a lesson stage, but each keeps its own student work.
export const practiceGroups = [
  {id:'announcer', title:'Main Task 1 · Visit and use each item', time:'14–27 min', pace:'Three short programs · about 4 minutes each',
    note:'Start with Scores, then try Badges and Training laps. Run and change the data on each card. Swap coder and checker after a card.',
    cards:['announcer','badges','laps'], checkpoint:'pitstop1'},
  {id:'desk', title:'Main Task 2 · Build and test a result', time:'35–50 min', pace:'Five short programs · about 3 minutes each',
    note:'Start with Score desk, then work through the scenarios. Use a hint when needed. Swap roles after a card; explain one update each.',
    cards:['desk','shelves','tickets','rainfall','supplies'], checkpoint:'pitstop2'},
];

const card = data => ({hints:[],steps:[],...data});
export const extraPractice = [
  card({id:'badges',group:'announcer',shortTitle:'Badges',skill:'Repeat with text',phase:'Main Task 1 · Practice 2 of 3',time:'About 4 min',
    title:'Print the club name badges',intro:'The club needs one name badge for each member.',
    learn:'A list can store text as well as numbers. Put each name in double quotes. A loop visits one name at a time; printing the loop variable displays that name, not the whole list.',
    example:'memberNames = ["Ari", "Bo"]\n\nfor currentName in memberNames:\n    print(currentName)\n',
    starter:'memberNames = ["Mia", "Sam", "Zara"]\n\n# Print each name on its own line.\n',
    check:'w2-badges',dataName:'memberNames',goal:'Use a for loop to print each name in memberNames on its own line. Print only the names.',
    steps:['Write and run the badge printer.','Add another name and run again.','Check work. Explain what currentName holds on one visit.'],
    discussion:'Two members have the same first name. Why does the loop still print two badges?',
    hints:['Use: for currentName in memberNames:','Indent print(currentName) by four spaces.'],
    solution:'memberNames = ["Mia", "Sam", "Zara"]\n\nfor currentName in memberNames:\n    print(currentName)\n',
    teacher:'The loop variable receives a string on each iteration. Identical names at different positions still cause separate visits. No conversion to int is needed.',
    tests:'["Mia", "Sam", "Zara"] -> Mia / Sam / Zara; ["Kai", "Kai"] prints Kai twice; [] prints nothing.',error:'Printing memberNames inside the loop repeats the entire list.'}),
  card({id:'laps',group:'announcer',shortTitle:'Training laps',skill:'Change each value',phase:'Main Task 1 · Practice 3 of 3',time:'About 4 min',
    title:'Double the training laps',intro:'Each runner wants a new target that is twice their current laps.',
    learn:'You can calculate a new value inside a loop. Multiply the current item by 2, store the answer, then print it. Both instructions repeat. This displays new targets without changing the original list.',
    example:'lapCounts = [2, 4]\n\nfor currentLaps in lapCounts:\n    targetLaps = currentLaps * 2\n    print(targetLaps)\n',
    starter:'lapCounts = [3, 0, 5, 2]\n\n# Calculate and print each doubled target.\n',
    check:'w2-laps',dataName:'lapCounts',goal:'Use a for loop. Print twice each value in lapCounts on a separate line, in order.',
    steps:['Calculate and print a target for each runner.','Run with a zero and two equal lap counts.','Check work. Explain one multiplication from your trace.'],
    discussion:'Which instructions must be indented so every runner gets a new target?',
    hints:['Inside the loop: targetLaps = currentLaps * 2','Print targetLaps inside the loop too.'],
    solution:'lapCounts = [3, 0, 5, 2]\n\nfor currentLaps in lapCounts:\n    targetLaps = currentLaps * 2\n    print(targetLaps)\n',
    teacher:'The outputs are 6, 0, 10 and 4. Each multiplication uses the current item. targetLaps is replaced on every visit; it is not a running total. The original list is unchanged.',
    tests:'[3, 0, 5, 2] -> 6 / 0 / 10 / 4; [2, 2] -> 4 / 4; [] -> no output.',error:'Printing currentLaps displays the original value. An unindented print displays only the final target for a non-empty list.'}),
  card({id:'shelves',group:'desk',shortTitle:'Library shelves',skill:'Count the items',phase:'Main Task 2 · Practice 2 of 5',time:'About 3 min',
    title:'Count the library shelves',intro:'Each list item tells you how many books are on one shelf. Find how many shelves were checked.',
    learn:'To count items, add 1 on each visit. The number of books on a shelf does not change that update. A shelf with zero books still counts as one shelf. Start the counter before the loop; print once after it.',
    example:'booksOnShelves = [3, 0]\nshelfCount = 0\n\nfor currentBooks in booksOnShelves:\n    shelfCount = shelfCount + 1\n\nprint(shelfCount)\n',
    starter:'booksOnShelves = [4, 0, 7, 2]\nshelfCount = 0\n\nfor currentBooks in booksOnShelves:\n    # Replace pass with the counter update.\n    pass\n\nprint(shelfCount)\n',
    check:'w2-shelves',dataName:'booksOnShelves',goal:'Use a for loop to count the items in booksOnShelves. Print only the shelf count.',
    steps:['Complete the counter and run.','Change a book count, then add a shelf. Run after each change.','Check work. Explain why an empty shelf is counted.'],
    discussion:'Which change increased the shelf count: changing a book value or adding another item?',
    hints:['Update with shelfCount = shelfCount + 1.','Add 1, not currentBooks.'],
    solution:'booksOnShelves = [4, 0, 7, 2]\nshelfCount = 0\n\nfor currentBooks in booksOnShelves:\n    shelfCount = shelfCount + 1\n\nprint(shelfCount)\n',
    teacher:'Four items mean four shelves. The values sum to 13 books, but that is not the requested result. The zero-book shelf increases shelfCount from 1 to 2.',
    tests:'[4, 0, 7, 2] -> 4; [0, 0] -> 2; [] -> 0.',error:'Adding currentBooks counts books instead of shelves.'}),
  card({id:'tickets',group:'desk',shortTitle:'Ticket income',skill:'Calculate, then total',phase:'Main Task 2 · Practice 3 of 5',time:'About 3 min',
    title:'Total the ticket income',intro:'Tickets cost RM 3 each. The list records how many tickets each group bought.',
    learn:'First calculate the income for one group. Then add that income to the running total. Both steps belong inside the loop. A new group changes groupIncome; totalIncome keeps the money collected so far.',
    example:'ticketCounts = [2, 1]\ntotalIncome = 0\n\nfor currentTickets in ticketCounts:\n    groupIncome = currentTickets * 3\n    totalIncome = totalIncome + groupIncome\n\nprint(totalIncome)\n',
    starter:'ticketCounts = [2, 0, 4, 1]\ntotalIncome = 0\n\nfor currentTickets in ticketCounts:\n    # Calculate this group\'s income at RM 3 per ticket.\n    # Add it to the running total.\n    pass\n\nprint(totalIncome)\n',
    check:'w2-tickets',dataName:'ticketCounts',goal:'Use a for loop to calculate total income at RM 3 per ticket. Print only the number, without RM.',
    steps:['Complete the two updates and run.','Test a group buying zero tickets.','Check work. Explain how one group changes the total.'],
    discussion:'What different values do currentTickets, groupIncome and totalIncome hold?',
    hints:['groupIncome = currentTickets * 3','totalIncome = totalIncome + groupIncome'],
    solution:'ticketCounts = [2, 0, 4, 1]\ntotalIncome = 0\n\nfor currentTickets in ticketCounts:\n    groupIncome = currentTickets * 3\n    totalIncome = totalIncome + groupIncome\n\nprint(totalIncome)\n',
    teacher:'Group incomes are 6, 0, 12 and 3. Running totals are 6, 6, 18 and 21. A correct loop that totals ticket counts then multiplies once by 3 also meets the task; ask the student to explain it.',
    tests:'[2, 0, 4, 1] -> 21; [1] -> 3; [] -> 0.',error:'Adding currentTickets directly without multiplying gives the ticket count rather than the income.'}),
  card({id:'rainfall',group:'desk',shortTitle:'Rainfall repair',skill:'Find and fix a bug',phase:'Main Task 2 · Practice 4 of 5',time:'About 3 min',
    title:'Repair the rainfall recorder',intro:'The recorder should add all the readings. It currently forgets the earlier rain.',
    learn:'A running total must keep its value between visits. Start it once before the loop. If you reset it inside the loop, each new visit loses the previous subtotal. Use Walk through to find when that happens.',
    example:'# A total that keeps earlier readings:\nrainfall = [2, 3]\ntotalRainfall = 0\n\nfor currentRainfall in rainfall:\n    totalRainfall = totalRainfall + currentRainfall\n\nprint(totalRainfall)\n',
    starter:'rainfall = [3, 0, 5, 2]\n\nfor currentRainfall in rainfall:\n    totalRainfall = 0\n    totalRainfall = totalRainfall + currentRainfall\n\nprint(totalRainfall)\n',
    check:'w2-rainfall',dataName:'rainfall',goal:'Repair the loop so it totals every value in rainfall. Print only the final total in millimetres.',
    steps:['Run the broken code; follow when the total returns to zero.','Move one line to repair it. Run again.','Check work. Explain why the repair keeps earlier readings.'],
    discussion:'Which line should run once, and which line should repeat for every reading?',
    hints:['Move totalRainfall = 0 before the for line.','Remove the four spaces from the line you moved.'],
    solution:'rainfall = [3, 0, 5, 2]\ntotalRainfall = 0\n\nfor currentRainfall in rainfall:\n    totalRainfall = totalRainfall + currentRainfall\n\nprint(totalRainfall)\n',
    teacher:'The broken program prints 2, the last reading. The repaired program prints 10. In the broken trace, the previous subtotal is erased at the start of every visit. An empty list also exposes a missing initial value.',
    tests:'[3, 0, 5, 2] -> 10; [0, 4] -> 4; [] -> 0.',error:'Changing the indentation of the update instead of the initial zero can leave only the last reading added.'}),
  card({id:'supplies',group:'desk',shortTitle:'Supply boxes',skill:'Combine two results',phase:'Main Task 2 · Practice 5 of 5',time:'About 3 min',
    title:'Check the classroom supply boxes',intro:'Each item records the pencils in one box. Report the number of boxes and the total pencils.',
    learn:'Use a counter for boxes and a running total for pencils. Start both at zero before the loop. Add 1 for each box and add the item value for its pencils. Print the two final results after the loop.',
    example:'pencilsInBoxes = [2, 0]\nboxCount = 0\ntotalPencils = 0\n\nfor currentPencils in pencilsInBoxes:\n    boxCount = boxCount + 1\n    totalPencils = totalPencils + currentPencils\n\nprint(boxCount)\nprint(totalPencils)\n',
    starter:'pencilsInBoxes = [6, 0, 3, 5]\n\n# Build a box count and a pencil total.\n# Print the box count, then the pencil total.\n',
    check:'w2-supplies',dataName:'pencilsInBoxes',goal:'Use a for loop. Print the box count first, then the total pencils, on separate lines.',
    steps:['Build both results. Use the example only if needed.','Run with an empty box and a different number of boxes.','Check work. Explain the two updates for the empty box.'],
    discussion:'An empty box has no pencils. Why does one result change while the other stays the same?',
    hints:['Start boxCount = 0 and totalPencils = 0 before the loop.','Inside the loop, count adds 1 and total adds currentPencils.'],
    solution:'pencilsInBoxes = [6, 0, 3, 5]\nboxCount = 0\ntotalPencils = 0\n\nfor currentPencils in pencilsInBoxes:\n    boxCount = boxCount + 1\n    totalPencils = totalPencils + currentPencils\n\nprint(boxCount)\nprint(totalPencils)\n',
    teacher:'The output is 4 boxes then 14 pencils. On the zero item, boxCount changes from 1 to 2 while totalPencils stays 6. Students transfer the score pattern to a different setting with meaningful variable names.',
    tests:'[6, 0, 3, 5] -> 4 then 14; [0] -> 1 then 0; [] -> 0 then 0.',error:'Starting boxCount at 1 adds a box that was never in the list.'}),
];
