import React, { useEffect, useRef, useState } from 'react';
import { CodeXml, BookOpen, Flag, Play, Square, ArrowRight, ArrowLeft, Download, Upload, List, X, IndentIncrease, IndentDecrease, Undo2, RotateCcw, Send, Check, Footprints, Lightbulb, GraduationCap } from 'lucide-react';
import { Editor } from '../Editor.jsx';
import { PythonRuntime, friendlyError } from '../runtime.js';
import { downloadFile } from '../storage.js';
import { recordAttempt } from '../evidence.js';
import { LearningReview } from '../LearningReview.jsx';
import { ReportPanel } from '../ReportPanel.jsx';
import { allTasks, lesson, coreTasks, extensions, coreChecks, meta, practiceFor, stageIndex, adjacentTask } from './content.js';
import { topics, reviewAt, updateReview, validateWeek2, reviewReport, stats } from './review.js';
import { Walkthrough, stepDescription } from './Walkthrough.jsx';
import teacherTraces from './teacher-traces.json';
import './week2.css';
const reportConfig = {...meta,allTasks,lesson:coreTasks,reviewReport};
function Dialog({title,onClose,children,wide=false}) {
  const ref=useRef();
  useEffect(()=>{ref.current.showModal();},[]);
  return <dialog ref={ref} className={'modal '+(wide?'wide':'')} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}} aria-label={title}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close"><X/></button></div>{children}</dialog>;
}
export function Week2App({profile,initialWork,onSave,onLeave}) {
  const [work,setWork]=useState(initialWork);
  const [taskId,setTaskId]=useState(allTasks.some(t=>t.id===initialWork.current)?initialWork.current:'ready');
  const [page,setPage]=useState('lesson'),[modal,setModal]=useState(null),[saved,setSaved]=useState(true),[toast,setToast]=useState('');
  const [status,setStatus]=useState('loading'),[runtimeMessage,setRuntimeMessage]=useState(''),[output,setOutput]=useState(''),[waiting,setWaiting]=useState(false),[answer,setAnswer]=useState(''),[error,setError]=useState(null),[feedback,setFeedback]=useState(null);
  const [trace,setTrace]=useState(null),[position,setPosition]=useState(0),[paused,setPaused]=useState(false),[example,setExample]=useState(null),[fontSize,setFontSize]=useState(17);
  const editor=useRef(),runtime=useRef(),active=useRef(),latest=useRef(),current=useRef(),input=useRef(),upload=useRef(),traceRef=useRef();
  const task=allTasks.find(t=>t.id===taskId)||lesson[0], index=stageIndex(task.id), practice=practiceFor(task.id);
  const code=example?.code ?? work.drafts?.[task.id] ?? task.starter ?? '';
  const busy=['running','checking','tracing'].includes(status);
  const selectedStep=trace?.steps[position];
  const summary=stats(work), hints=work.hints?.[task.id]||0;
  current.current={task,code,example}; latest.current={...work,current:task.id};traceRef.current=trace;
  useEffect(()=>{const timer=setTimeout(()=>setSaved(onSave({...work,current:taskId})),250);return()=>clearTimeout(timer);},[work,taskId]);
  useEffect(()=>{const persist=()=>onSave(latest.current);window.addEventListener('pagehide',persist);return()=>{persist();window.removeEventListener('pagehide',persist);};},[]);
  useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(timer);}},[toast]);
  useEffect(()=>{if(waiting)input.current?.focus({preventScroll:true});},[waiting]);
  useEffect(()=>{
    runtime.current=new PythonRuntime({
      status:(value,message='')=>{setStatus(value);setRuntimeMessage(message);if(value==='unavailable'){setWaiting(false);setPaused(false);}},
      output:text=>{if(active.current)active.current.output+=text;setOutput(old=>old+text);},
      input:()=>{setWaiting(true);setAnswer('');},
      trace:(step,isPaused)=>{setTrace(old=>{const next={...(old||{}),steps:[...(old?.steps||[]),step]};setPosition(next.steps.length-1);return next;});setPaused(isPaused);},
      finish:data=>{
        setWaiting(false);setPaused(false);
        const attempt=active.current;
        if(attempt && attempt.kind!=='trace' && !attempt.example)setWork(old=>recordAttempt(old,attempt,data));
        if(data.type==='checked'){
          setFeedback(data.result);
          if(data.result.passed && attempt)setWork(old=>({...old,passed:{...old.passed,[attempt.taskId]:attempt.code}}));
        }else if(data.type==='error'){
          const traceNotice = attempt?.kind === 'trace' && /Walk ?through|Walkthrough/.test(data.message);
          const message=data.stopped?'Program stopped. Your code is kept.':traceNotice?data.message.split('\n').filter(Boolean).at(-1):friendlyError(data.message).tip;
          setError({message,detail:data.message});
          if(attempt?.kind==='trace')setTrace(old=>old?{...old,error:data.stopped?message:data.message.split('\n').filter(Boolean).at(-1)}:old);
        }
        active.current=null;
      },
    });runtime.current.start();return()=>runtime.current.destroy();
  },[]);
  function clearRun(){setOutput('');setFeedback(null);setError(null);setWaiting(false);setTrace(null);setPaused(false);setPosition(0);}
  function selectTask(id){if(runtime.current?.active){setToast('Stop the program before changing tasks.');return;}setTaskId(id);setPage('lesson');setModal(null);setExample(null);clearRun();setWork(old=>({...old,visited:{...old.visited,[id]:true}}));window.scrollTo({top:0,behavior:'smooth'});}
  function changeCode(value){if(runtime.current?.active)return;setTrace(null);setFeedback(null);if(example)setExample(old=>({...old,code:value}));else setWork(old=>({...old,drafts:{...old.drafts,[task.id]:value}}));}
  function run(kind='run'){
    const {task:liveTask,code:liveCode,example:liveExample}=current.current;
    if(!runtime.current?.ready||runtime.current.active)return;
    clearRun();
    active.current={taskId:liveTask.id,code:liveCode,kind,example:!!liveExample,inputs:[],output:'',startedAt:new Date().toISOString()};
    if(kind==='trace'){
      setTrace({code:liveCode,example:!!liveExample,steps:[]});
      setWork(old=>({...old,traceUses:{...old.traceUses,[liveTask.id]:(old.traceUses?.[liveTask.id]||0)+1}}));
      runtime.current.walk(liveCode);
    }else{
      if(!liveExample)setWork(old=>({...old,attempted:{...old.attempted,[liveTask.id]:true}}));
      runtime.current.execute(liveCode,kind==='check'?liveTask.check:null);
    }
  }
  function nextTrace(iteration){
    const steps=trace.steps;
    if(position<steps.length-1){const target=iteration?steps.findIndex((s,i)=>i>position&&(s.iterationChanged||s.loopFinished||s.event==='end')):position+1;setPosition(target<0?steps.length-1:target);return;}
    if(runtime.current.nextTrace(iteration))setPaused(false);
  }
  function submitAnswer(e){e.preventDefault();try{if(runtime.current.answer(answer)){if(active.current){active.current.inputs.push(answer);active.current.output+=answer+'\n';}setOutput(old=>old+answer+'\n');setWaiting(false);setAnswer('');}}catch(err){setToast(err.message);}}
  function explore(code,title='Worked example'){if(busy)return;clearRun();setExample({code,title});setWork(old=>({...old,reading:{...old.reading,[task.id]:true}}));}
  function keepStep(step){setWork(old=>({...old,traceEvidence:{...old.traceEvidence,[task.id]:{code:trace.code,description:stepDescription(step,trace.example),savedAt:new Date().toISOString()}}}));setToast('This step is saved in your Week 2 report. Add your own explanation below.');}
  function backup(){downloadFile('kl-coding-week-2-backup.json',JSON.stringify({format:'kl-coding-lab-backup',version:3,lesson:2,student:{name:profile.name,className:profile.className},work:{...work,drafts:work.drafts||{},current:task.id}},null,2),'application/json');}
  async function importFile(e){const file=e.target.files?.[0];if(!file)return;try{if(file.size>5000000)throw Error('Choose a file smaller than 5 MB.');const text=await file.text();if(file.name.endsWith('.json')){const data=JSON.parse(text);if(data.format!=='kl-coding-lab-backup'||data.lesson!==2)throw Error('Choose a Week 2 backup. Open Week 1 to restore Week 1 work.');const imported=validateWeek2(data.work);setWork(old=>({...old,...imported,drafts:{...old.drafts,...imported.drafts}}));if(imported.current)setTaskId(imported.current);setExample(null);setToast('Week 2 backup restored to '+profile.name+'.');}else{changeCode(text);setToast('Python file opened.');}clearRun();setModal(null);}catch(err){setToast(err.message);}e.target.value='';}
  function leave(){if(busy)return;if(onSave(latest.current))onLeave();else setToast('Download a backup first: saving is unavailable.');}
  function continueLesson(){const next=adjacentTask(task.id,1);if(next)selectTask(next);else setModal('report');}
  const nextButtons=<div className="card-bottom"><button className="text-button" disabled={busy||index===0} onClick={()=>task.level?setPage('extensions'):selectTask(adjacentTask(task.id,-1))}><ArrowLeft size={16}/>{task.level?'All extensions':'Back'}</button><span>{task.level?'Any level is open':practice?`Practice ${practice.cards.indexOf(task.id)+1} of ${practice.cards.length}`:`Stage ${index+1} of ${lesson.length}`}</span><button className="primary-button" disabled={busy} onClick={()=>task.level?setPage('extensions'):continueLesson()}>{task.level?'All extensions':index===lesson.length-1?'My report':practice&&practice.cards.at(-1)!==task.id?'Next practice':'Continue'}<ArrowRight size={17}/></button></div>;
  return <div className="week-two">
    <header className="topbar"><button className="brand brand-button" onClick={()=>setPage('lesson')}><span className="brand-mark"><CodeXml size={25}/></span><span>KL <b>Coding Lab</b></span></button><nav className="main-nav" aria-label="Week 2 navigation"><button className={page==='lesson'?'active':''} onClick={()=>setPage('lesson')}><BookOpen size={18}/>Lesson</button><button className={page==='extensions'?'active':''} onClick={()=>setPage('extensions')}><Flag size={18}/>Extensions</button></nav><button className="quiet-button" aria-label="Teacher guide" onClick={()=>setModal('teacher')}><GraduationCap size={18}/><span className="teacher-label">Teacher guide</span></button></header>
    <main><div className="student-bar"><div><span className="student-avatar">{profile.name.slice(0,1)}</span><span><b>{profile.name}</b><small>{profile.className} · Week 2</small></span><button className="text-button" disabled={busy} onClick={leave}>Change week / student</button></div><div><button className="outline-button" onClick={()=>setModal('files')}><Download size={17}/>My files</button><button className="outline-button" onClick={()=>setModal('report')}>My learning report</button></div></div>
    <div className="lesson-heading"><div><div className="eyebrow">WEEK 02 · 15 SEPTEMBER 2026 · 60 MINUTES</div><h1>Lists, loops & running totals</h1><p className="week-subtitle">Read a little. Follow a value. Build something you can explain.</p></div><button className="outline-button" onClick={()=>setModal('map')}><List size={17}/>Lesson map</button></div>
    {page==='extensions'?<section className="week-extensions"><div className="eyebrow">CHOOSE YOUR NEXT CHALLENGE</div><h2>Let your learning grow</h2><p>Every route is open to everyone. Choose support or stretch whenever it helps.</p><div className="challenge-grid">{extensions.map(item=><button key={item.id} className={'challenge-card '+item.colour} disabled={busy} onClick={()=>selectTask(item.id)}><span className={'level-pill '+item.colour}>{item.level}</span><h3>{item.title}</h3><p>{item.intro}</p><span className="challenge-go">Read & try <ArrowRight size={18}/></span></button>)}</div><button className="text-button" onClick={()=>setPage('lesson')}><ArrowLeft size={17}/>Back to my task</button></section>:<>
      <div className="progress-strip"><div className="steps-track" aria-label="Week 2 lesson steps">{lesson.map((item,i)=><button key={item.id} disabled={busy} className={index===i?'current':''} aria-label={`${i+1}. ${item.title}`} aria-current={index===i?'step':undefined} onClick={()=>selectTask(item.id)}>{i+1}</button>)}</div><span>{summary.passed} of {coreChecks} core practice checks passed</span></div>
      {practice&&<section className="practice-bank" aria-label={practice.title}>
        <div className="practice-heading"><div><span className="eyebrow">{practice.time} · {practice.pace}</span><h2>{practice.title}</h2></div><button className="outline-button" disabled={busy} onClick={()=>selectTask(practice.checkpoint)}>Go to learning pit stop <ArrowRight size={16}/></button></div>
        <p>{practice.note}</p>
        <nav className="practice-cards" aria-label="Choose a practice card">{practice.cards.map((id,i)=>{const item=allTasks.find(t=>t.id===id),passed=work.passed?.[id]!==undefined&&work.passed[id]===(work.drafts?.[id]??item.starter);return <button key={id} disabled={busy} aria-current={id===task.id?'step':undefined} onClick={()=>selectTask(id)}><span className="practice-number">{passed?<Check size={17}/>:i+1}</span><span><b>{item.shortTitle}</b><small>{item.skill}</small><em>{passed?'Current code passed':work.attempted?.[id]?'In progress':'Ready to try'}</em></span></button>;})}</nav>
        <p className="practice-pacing">Aim to try each scenario. When your teacher calls the pit stop, pause and reflect; unfinished cards stay available. Each card saves its own program.</p>
      </section>}
      {task.kind==='review'?<><p className="week-phase">{task.phase} · {task.time}</p><LearningReview key={task.id} topics={topics} checkpointLabel={task.checkpoint==='pitstop1'?'Learning pit stop 1':'Learning pit stop 2'} after={!!task.checkpoint} work={{learningReview:reviewAt(work,task.id)}} setWork={updater=>setWork(old=>updateReview(old,task.id,updater({learningReview:reviewAt(old,task.id)}).learningReview))} saved={saved} onOpen={selectTask} onBack={()=>selectTask(adjacentTask(task.id,-1))} onContinue={continueLesson}/>{task.id==='pitstop2'&&<p className="review-note">Pit Stop 1 is kept separately in your report. Your new reflection will not overwrite it.</p>}</>:task.kind==='welcome'?<section className="week-ready"><span className="card-type">{task.phase} · {task.time}</span><h2>{task.title}</h2><p>{task.intro}</p><div className="ready-grid"><div><BookOpen/><h3>Read, try, explain</h3><p>{task.learn}</p></div><div><CodeXml/><h3>Our roles</h3><p>The coder types and runs. The checker asks “What changed?” and suggests a test. Swap during each main task. Each person explains one step independently.</p></div><div><Footprints/><h3>Choose your next step</h3><p>Use a small example, ask for help or open an extension. No level is locked. Keep your own code and explanation in your report.</p></div></div><div className="week-talk"><b>Talk together</b><p>{task.discussion}</p></div>{nextButtons}</section>:<div className="workspace week-workspace">
        <section className="learning-panel" aria-label="Week 2 learning card"><div className="card-meta"><span className="card-type">{task.phase}</span><span>{task.time}</span></div><h2>{task.title}</h2><p className="card-intro">{task.intro}</p>
          <div className="learn-box"><div className="box-label"><BookOpen size={17}/>READ FIRST</div><p>{task.learn}</p>{task.example&&<><pre className="example"><code>{task.example}</code></pre><button className="outline-button" disabled={busy} onClick={()=>explore(task.example)}><Footprints size={17}/>Explore this example</button><p className="review-note">Your own code stays in its place.</p></>}{task.extraExamples?.map(item=><details className="extra-example" key={item.title}><summary>{item.title}</summary><pre className="example"><code>{item.code}</code></pre><button className="outline-button" disabled={busy} onClick={()=>explore(item.code,item.title)}>Explore this example</button></details>)}<button className="text-button" onClick={()=>setWork(old=>({...old,reading:{...old.reading,[task.id]:true}}))}><Check size={16}/>{work.reading?.[task.id]?'Reading recorded':'I have read this'}</button></div>
          <div className="week-talk"><b>Think & discuss after running</b><p>{task.discussion}</p></div><div className="task-box"><div className="box-label"><Flag size={16}/>TRY IT YOURSELF</div><ol>{task.steps.map((step,i)=><li key={i}>{step}</li>)}</ol></div>
          {task.scaffold&&<details className="week-support"><summary>Need a missing-line starter?</summary><pre className="example"><code>{task.scaffold}</code></pre><button className="outline-button" disabled={busy} onClick={()=>setModal('scaffold')}>Use this starter</button></details>}
          {task.hints.length>0&&<div className="hint-box"><button className="hint-toggle" disabled={hints>=task.hints.length} onClick={()=>setWork(old=>({...old,hints:{...old.hints,[task.id]:hints+1}}))}><Lightbulb size={17}/>{hints?'Another small hint':'Need a small hint?'}</button>{task.hints.slice(0,hints).map((hint,i)=><p key={i}>{hint}</p>)}</div>}
          {task.extension&&<details className="extension"><summary>Try a variation</summary><p>{task.extension}</p></details>}{nextButtons}
        </section>
        <section className="coding-panel" aria-label="Python workspace">
          {example&&<div className="example-banner"><div><b>Exploring: {example.title}</b><p>Practice here. Your own program is kept separately.</p></div><button className="outline-button" disabled={busy} onClick={()=>{setExample(null);clearRun();}}>Back to my code</button></div>}
          <div className="editor-frame"><div className="editor-heading"><b className="file-label"><span className="py-icon">PY</span>{example?'example.py':'main.py'}</b><span className="runtime-status">{({loading:'Starting Python…',ready:'Python ready',running:'Running',checking:'Checking',tracing:waiting?'Waiting for input':paused?'Paused at a step':'Tracing',unavailable:'Python needs attention'})[status]}</span></div><div className="editor-tools"><div><button disabled={busy} onClick={()=>editor.current?.indent()} aria-label="Indent code"><IndentIncrease size={17}/>Indent</button><button disabled={busy} onClick={()=>editor.current?.outdent()} aria-label="Outdent code"><IndentDecrease size={17}/>Outdent</button><button disabled={busy} onClick={()=>editor.current?.undo()} aria-label="Undo code change"><Undo2 size={17}/>Undo</button></div><div><button onClick={()=>setFontSize(s=>s===21?15:s+2)} aria-label="Change code text size">Aa</button><button disabled={busy} onClick={()=>setModal('reset')} aria-label="Reset this task"><RotateCcw size={17}/></button></div></div>
            <Editor key={task.id+(example?'-example':'')} ref={editor} value={code} onChange={changeCode} onRun={()=>run()} readOnly={busy} fontSize={fontSize} executedLine={selectedStep?.executedLine} nextLine={selectedStep?.nextLine}/>
            <div className="runbar"><button className="run-button" disabled={status!=='ready'} onClick={()=>run()}><Play size={16}/>Run</button><button className="walk-button" disabled={status!=='ready'} onClick={()=>run('trace')}><Footprints size={17}/>Walk through</button><button className="stop-button" disabled={!busy} onClick={()=>runtime.current.stop()}><Square size={13}/>Stop</button><button className="editor-download" aria-label="Download Python file" onClick={()=>downloadFile(`kl-coding-week-2-${task.id}.py`,code)}><Download size={18}/></button></div></div>
          <div className="console-frame"><div className="console-heading"><b>Console</b><span>{waiting?'Type an answer and press Enter':trace?'Latest live output':'Program output'}</span></div><div className="console-body" tabIndex={0} aria-label="Program output"><pre>{output || (status==='loading'?'Python is loading. Read the card while you wait.':trace?'No output yet. Follow the walkthrough below.':'Run your program or walk through one line at a time.')}</pre>{error&&<div className="python-error" role="alert"><b>{error.message}</b><details><summary>Read the Python error</summary><pre>{error.detail}</pre></details></div>}</div>{waiting&&<form className="console-input" onSubmit={submitAnswer}><label className="sr-only" htmlFor="week2-input">Your answer to the Python prompt</label><input ref={input} id="week2-input" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Type an answer, then press Enter" autoComplete="off" autoCapitalize="off" spellCheck="false" enterKeyHint="send"/><button aria-label="Send answer" type="submit"><Send size={18}/></button></form>}{status==='unavailable'&&<div className="runtime-error"><p>{runtimeMessage}</p><button className="outline-button" onClick={()=>runtime.current.start()}>Try loading Python again</button></div>}</div>
          {trace&&<Walkthrough trace={trace} position={position} paused={paused} busy={status==='tracing'} waiting={waiting} onPosition={setPosition} onNext={nextTrace} onRestart={()=>run('trace')} onStop={()=>runtime.current.stop()} onSave={keepStep} onClose={()=>setTrace(null)}/>}
          {task.check&&!example&&<><div className="check-panel"><b>{work.passed?.[task.id]===code?'Your current code passed':'Ready to check?'}</b><button className="outline-button" disabled={status!=='ready'} onClick={()=>run('check')}><Check size={17}/>Check work</button></div><p className="check-goal">{task.goal}</p><p className="review-note">Checks try fresh lists by replacing the first <code>{task.dataName||'scores'}</code> assignment. Keep that name. Your editor code is not changed.</p></>}
          {feedback&&<div className={'feedback '+(feedback.passed?'success':'retry')} role="status"><b>{feedback.message}</b>{feedback.error&&<pre>{feedback.error}</pre>}{feedback.cases?.map((item,i)=><details key={i}><summary>Test {i+1} · {item.passed?'Passed':'Try again'}</summary><p><b>Test data</b></p><pre>{item.input}</pre><p><b>Expected</b></p><pre>{item.expected||'(no output)'}</pre><p><b>Your output</b></p><pre>{item.actual||'(no output)'}</pre>{item.error&&<pre>{item.error}</pre>}</details>)}</div>}
          <details className="explain-program"><summary>Explain my program <span>Included in my report</span></summary><label htmlFor="week2-explain">What changed, and why? Use actual values from a run.</label><textarea id="week2-explain" maxLength={3000} rows={3} value={work.explanations?.[task.id]||''} onChange={e=>setWork(old=>({...old,explanations:{...old.explanations,[task.id]:e.target.value}}))} placeholder={task.group==='announcer'?"On iteration… the current item was… My program displayed… because…":"The old value was… I added… The new value became…"}/>{work.traceEvidence?.[task.id]&&<p>One selected trace step is included with this task.</p>}</details><div className="workspace-foot"><span>{saved?'Saved on this device':'Saving unavailable — download a backup'}</span><span>Week 2 work</span></div><p className="keyboard-note">Four-space indentation · Ctrl / ⌘ + Enter runs · Escape, then Tab leaves the editor</p>
        </section></div>}
    </>}
    </main><footer><span>KL Coding Cup · Week 2 practice</span><span>Read · Explore · Build · Test · Explain</span></footer>
    {toast&&<div className="toast" role="status">{toast}</div>}
    <input className="sr-only" ref={upload} type="file" accept=".py,.txt,.json" onChange={importFile} aria-label="Import Week 2 code or backup"/>
    {modal==='map'&&<Dialog title="Week 2 lesson map" onClose={()=>setModal(null)}><p>Your draft stays with each task. Every stage is open.</p><div className="lesson-map">{lesson.map((item,i)=><button disabled={busy} key={item.id} onClick={()=>selectTask(item.id)}><span className="map-number">{i+1}</span><span><b>{practiceFor(item.id)?.title||item.title}</b><small>{item.phase} · {item.time}{practiceFor(item.id)?` · ${practiceFor(item.id).cards.length} practice cards`:""}</small></span></button>)}</div></Dialog>}
    {modal==='report'&&<Dialog title="My Week 2 learning report" onClose={()=>setModal(null)}><ReportPanel profile={profile} work={work} setWork={setWork} busy={busy} onBackup={backup} lessonConfig={reportConfig}/></Dialog>}
    {modal==='files'&&<Dialog title="Keep my Week 2 work" onClose={()=>setModal(null)}><p>Week 2 code, reflections and traces are saved separately from Week 1.</p><div className="file-actions"><button onClick={()=>setModal('report')}><Download/><span><b>My learning report (PDF)</b><small>Code, tests, both pit stops and my selected trace steps</small></span></button><button onClick={backup}><Download/><span><b>Download Week 2 backup</b><small>Restore it on another device</small></span></button><button disabled={busy} onClick={()=>{backup();upload.current.click();}}><Upload/><span><b>Import Python or a Week 2 backup</b><small>Your current backup downloads first</small></span></button></div><p className="review-note">The app saves in this browser. It does not sync devices or upload to Teams automatically.</p></Dialog>}
    {(modal==='reset'||modal==='scaffold')&&<Dialog title={modal==='scaffold'?'Use the supported starter?':'Reset this editor?'} onClose={()=>setModal(null)}><p>Your current Python file will download first, so you can keep it.</p><button className="primary-button" disabled={busy} onClick={()=>{downloadFile(`week2-${task.id}-before-change.py`,code);changeCode(modal==='scaffold'?task.scaffold:task.starter||'');setModal(null);}}>Download current code & replace</button></Dialog>}
    {modal==='teacher'&&<Dialog title="Week 2 · teacher guide" wide onClose={()=>setModal(null)}><p>15 September · 60 minutes · KS2–KS4. Use short explanations, then coach students as they work.</p><div className="teacher-objective"><b>Learning intention</b><p>Write and test loops that process a list, then explain how counts and totals change.</p></div><div className="table-scroll"><table><thead><tr><th>Minutes</th><th>Stage</th><th>Teacher role</th></tr></thead><tbody>{lesson.map(t=><tr key={t.id}><td>{t.time}</td><td>{t.phase}</td><td>{t.kind==='review'?'Ask for code or trace evidence; agree one next action.':t.id==='ready'?'Establish coder/checker roles.':t.id==='loop'||t.id==='totals'?'Model for at most two minutes, then let students explore.':practiceFor(t.id)?`${practiceFor(t.id).cards.length} short programs. Swap roles after a card; pause everyone at the pit stop.`:'Coach small steps. Ask students to explain actual values.'}</td></tr>)}</tbody></table></div><div className="teacher-differentiation"><div><b>KS2 support</b><p>Short lists, one result at a time, missing-line starters.</p></div><div><b>KS3 support</b><p>Less starter code; combine count and total.</p></div><div><b>KS4 stretch</b><p>Conditions, functions and one-pass reasoning.</p></div></div><p>These guide support, not access. Every extension is open to every student.</p><p>Model meaningful camelCase names and explicit updates. Four spaces show each block. Accept other correct, explainable code when it meets the stated task.</p><a className="outline-button" href="./week-2-teacher-guide.md" download>Download teacher reference</a><p>Main Task 1 has three scenarios (about 4 minutes each). Main Task 2 has five (about 3 minutes each). Treat these as flexible practice windows, including reading, coding and checking. Keep the pit stops at minutes 27 and 50 even if some cards are unfinished. Use a worked example or hint for support; invite confident students to work with less help.</p><h3>Solutions, line explanations & test answers</h3>{allTasks.filter(t=>t.solution||t.teacher).map(t=><details className="teacher-answer" key={t.id}><summary>{t.level?t.level+' · ':''}{t.title}</summary><p>{t.teacher}</p><pre className="example"><code>{t.solution||t.example}</code></pre><p><b>Expected tests:</b> {t.tests}</p><p><b>Common error:</b> {t.error}</p>{teacherTraces[t.id]&&<details><summary>See every line and iteration in this model</summary><div className="table-scroll"><table><thead><tr><th>Line</th><th>Iteration</th><th>Explanation</th></tr></thead><tbody>{teacherTraces[t.id].map((step,i)=><tr key={i}><td>{step.line||'Start'}</td><td>{step.iteration||'—'}</td><td>{step.explanation}</td></tr>)}</tbody></table></div></details>}</details>)}</Dialog>}
  </div>;
}
