export const lesson = [
  {
    id: 'hello', phase: 'Do now', time: '2–7 min', title: 'Make Python say hello',
    intro: 'Your first program is ready. Run it, then make it yours.',
    learn: 'print() displays a message. Put words inside quotation marks. Python follows your instructions from top to bottom.',
    example: 'print("Hello, coding club!")',
    task: 'Write your own welcome message.',
    steps: ['Press Run. Read the message in the console.', 'Change the words inside the quotes.', 'Add another print() line and run your program again.'],
    starter: 'print("Hello, coding club!")\n',
    hints: ['Keep a quote at the beginning and end of your message.', 'Each print() can go on a new line.', 'For example: print("Ready for a challenge!")'],
    check: 'hello', goal: 'Display two non-empty lines, including your own message.',
    vocab: ['Output', 'Information a program displays.'],
  },
  {
    id: 'goal', phase: 'Our learning', time: '7–10 min', title: 'Small steps. Your own code.',
    intro: 'Today: write and test a program that takes input and produces useful output.',
    learn: 'Read → Run → Change → Build → Check. Work at a pace that helps you understand. Every challenge level is open to everyone.',
    concepts: [ ['Knowledge', 'What input, output and a variable mean.'], ['Skills', 'Edit, run, enter an answer, debug and save.'], ['Understanding', 'Explain how input changes a result and how testing helps.'] ],
    task: 'Be the owner of your code.',
    steps: ['Try an idea, read what happens and make a change.', 'Use a hint or ask for help when you need it.', 'With a partner: the coder types; the checker suggests tests. Swap roles.'],
    starter: '# Try a message of your own.\n', hints: ['You can return to any card using Lesson map.'],
  },
  {
    id: 'variable', phase: 'Learn & try', time: '10–18 min', title: 'Keep a value in a variable',
    intro: 'A variable gives a value a name so you can use it again.',
    learn: 'The equals sign stores the value on the right under the name on the left. Use that name without quotes to display its value.',
    example: 'club = "Code Explorers"\nprint(club)',
    task: 'Give your club a name and display it twice.',
    steps: ['Run the example.', 'Change the club name in the first line.', 'Use the variable in another print() line. Run again.'],
    starter: 'club = "Code Explorers"\nprint(club)\n',
    hints: ['Change the words inside quotes on line 1.', 'print(club) displays the value. print("club") displays the word club.', 'Add another line: print(club)'],
    check: 'variable', goal: 'Store a club name in a variable and display its value twice.',
    vocab: ['Variable', 'A name that refers to a stored value.'],
  },
  {
    id: 'input', phase: 'Learn & try', time: '18–22 min', title: 'Ask the coder a question',
    intro: 'Let the person running your program choose the answer.',
    learn: 'input() asks a question and waits. Type your answer in the console and press Enter. The variable keeps the answer so your program can use it.',
    example: 'coder = input("Choose a coder name: ")\nprint("Welcome,", coder)',
    task: 'Make a welcome that changes with the answer.',
    steps: ['Run the program. Enter a made-up coder name in the console.', 'Change the welcome message.', 'Run again with a different name. Check that the new name appears.'],
    starter: 'coder = input("Choose a coder name: ")\nprint("Welcome,", coder)\n',
    hints: ['The answer belongs in the console, below your code.', 'Use the variable coder in your print() line.', 'A comma in print("Hello,", coder) separates the message and the value.'],
    check: 'input', goal: 'Read one answer and include it in your output for different inputs.',
    vocab: ['Input', 'Information a person gives to a program.'],
  },
  {
    id: 'welcome', phase: 'Main task 1', time: '22–27 min', title: 'Build the club welcome',
    intro: 'Your coding club is welcoming new members. Make a program that gets to know them.',
    learn: 'Use a different variable for each answer you want to keep. Your own wording is welcome.',
    task: 'Ask for a coder name and a favourite activity. Display both answers in a welcome.',
    steps: ['Write the two questions in your editor.', 'Use both stored answers in your message.', 'Test twice with different answers, then select Check work.'],
    starter: '# Ask for a coder name.\n\n# Ask for a favourite activity.\n\n# Welcome the coder and mention the activity.\n',
    hints: ['You need two input() calls and two variable names.', 'Choose names such as coder and activity.', 'Start with: coder = input("Coder name: ")'],
    check: 'welcome', goal: 'Read two answers and display both. Check work tries two pairs of answers.',
  },
  {
    id: 'pitstop', phase: 'Learning pit stop', time: '27–31 min', title: 'Choose your next step',
    intro: 'Pause for a moment. How is this task feeling right now?',
    learn: 'Choose the support that helps you learn. You can change your choice as you go.',
    kind: 'pitstop', task: 'Name one thing you can do and one thing you want to try.',
    steps: ['Choose a next step below.', 'Tell a partner or your teacher what would help.'],
    starter: '# A space to try an idea.\n', hints: ['A useful question: “I want my program to ___. It currently ___.”'],
  },
  {
    id: 'numbers', phase: 'Main task 2 · optional primer', time: '31–38 min', title: 'Turn answers into numbers',
    intro: 'The score desk needs to add points. First, tell Python these answers are whole numbers.',
    learn: 'input() gives you text. int() converts suitable text to a whole number. Use + to add numbers. For this task, enter whole numbers such as 4 or 12.',
    example: 'score = int(input("Points: "))\nprint(score + 1)',
    task: 'Ask for two scores and display their total.',
    steps: ['Run this one-score example.', 'Read a second whole-number score into another variable.', 'Print their sum. Test with 4 and 7, then with 0 and 9.'],
    starter: 'score = int(input("Points: "))\nprint(score + 1)\n',
    hints: ['Use int(input(...)) for each score.', 'Use different variable names for the two scores.', 'If your variables are first and second, add them with first + second.'],
    check: 'total', goal: 'Read two whole numbers and print only their sum, apart from input prompts.',
    vocab: ['Integer', 'A whole number, such as 0, 12 or −3.'],
  },
  {
    id: 'debug', phase: 'Practice & help', time: 'Use when helpful', title: 'Find it. Fix it. Run again.',
    intro: 'An error message is a clue. Start with the line Python points to.',
    learn: 'Check matching quotes and brackets. Variable names must match exactly. Make one small change, then run again. Indented blocks use four spaces; the Indent and Outdent buttons can help.',
    task: 'Fix the message so it displays Ready to code!',
    steps: ['Run the program and read the error.', 'Find the missing character and fix it.', 'Run again. Explain your change to a partner.'],
    starter: 'print("Ready to code!)\n',
    hints: ['Check the pair of quotation marks.', 'There is an opening quote but no closing quote.', 'Put a closing quote just before the final bracket.'],
    check: 'debug', goal: 'Display exactly Ready to code! on one line.',
  },
  {
    id: 'choose', phase: 'Main task 2', time: '38–53 min', title: 'Choose a challenge',
    intro: 'Build something you can explain. Pick the challenge that gives you a useful next step.',
    learn: 'All four routes are open. You can revisit a learning card or try another route at any time. Your code is saved separately for each task.',
    task: 'Choose a scenario, build a solution and test it.',
    steps: ['Read the task and its examples.', 'Break it into small actions and write your code.', 'Try different inputs. Use Check work when you are ready.'],
    starter: '# Use Challenges to choose your next task.\n', kind: 'choose',
    hints: ['Start with the club welcome if input() is new. Try the score desk if you are ready to use numbers.'],
  },
  {
    id: 'reflect', phase: 'Plenary', time: '53–60 min', title: 'Show what you can do',
    intro: 'Choose one program you made today. Run it and explain a part you wrote yourself.',
    learn: 'A useful reflection names something specific: a change, a test or an error you fixed.',
    task: 'Keep your work and choose a next step.',
    steps: ['Open your best task and demonstrate it with a new input.', 'Add an explanation of your program, then complete the reflection below.', 'Download your learning report as a PDF and attach it to your teacher’s Teams assignment.'],
    starter: '# Return to a task to demonstrate your program.\n', kind: 'reflect',
    hints: ['Try: “I tested ___ because ___. Next I want to ___.”'],
  },
];

export const challenges = [
  {
    id: 'prebronze', level: 'Pre-Bronze', colour: 'mint', title: 'The welcome desk',
    summary: 'Make a personal welcome for your coding club.', conceptsLabel: 'Input · variables · output', phase: 'Build', time: 'Work at your pace',
    intro: 'A new coder has arrived. Your program should help them feel welcome.',
    learn: 'Use two input() calls to collect a coder name and a favourite activity. Store each answer separately.',
    task: 'Display a welcome that includes both answers.',
    steps: ['Ask for the coder name, then the favourite activity.', 'Display both answers in a useful message.', 'Test two different pairs of answers.'],
    starter: '# 1. Ask for a coder name.\n\n# 2. Ask for a favourite activity.\n\n# 3. Display a welcome using both answers.\n',
    hints: ['You can revisit “Ask the coder a question” in Lesson map.', 'Use one variable for each answer.', 'print("Welcome,", coder) can display one of your answers. How will you use the other?'],
    check: 'welcome', goal: 'Read two answers and display both. Wording is your choice.',
    extension: 'Ask a third question and use its answer. Download this version before extending it; Check work covers the original two-question task.',
  },
  {
    id: 'bronze', level: 'Bronze', colour: 'amber', title: 'The score desk',
    summary: 'Add two rounds of points for a competition.', conceptsLabel: 'Input · integers · addition', phase: 'Build', time: 'Work at your pace',
    intro: 'A player completes two rounds. The score desk needs their total points.',
    learn: 'Convert each answer with int() before adding. You can use a prompt inside input(), but print only the final number as your answer.',
    task: 'Read two whole-number scores, one per input, and print their sum.',
    sample: [{input: '4\n7', output: '11'}, {input: '0\n9', output: '9'}],
    steps: ['Read and convert the first score.', 'Read and convert the second score.', 'Add the scores and display the answer.'],
    starter: '# Read the first score.\n\n# Read the second score.\n\n# Print the total.\n',
    hints: ['Need a reminder? Open “Turn answers into numbers” in Lesson map.', 'int(input("Score: ")) reads a whole number.', 'Add your two variables inside print().'],
    check: 'total', goal: 'Read two integers and print only their sum, apart from input prompts.',
    extension: 'Create a three-round version. Keep a downloaded copy of your two-round solution; the checks cover two rounds.',
  },
  {
    id: 'silver', level: 'Silver', colour: 'slate', title: 'Spot the repeat scores',
    summary: 'Count the entries whose scores appear again.', conceptsLabel: 'Lists · loops · counting', phase: 'Extend', time: 'Can continue next lesson',
    intro: 'Some scores appear more than once. Count every entry belonging to a repeated score.',
    learn: 'In 3, 5, 3, 2, 5, 8, both 3s and both 5s count. The answer is 4. Count entries, rather than only the distinct repeated values.',
    task: 'Read space-separated integers on one line. Print how many entries have a value that occurs more than once.',
    sample: [{input: '3 5 3 2 5 8', output: '4'}, {input: '4 4 4 1', output: '3'}],
    steps: ['Turn the line of input into a list of integers.', 'Find how often each value appears.', 'Count the entries with a frequency greater than one.'],
    starter: 'scores = [int(value) for value in input("Scores: ").split()]\n\n# Count entries whose value occurs more than once.\n',
    hints: ['scores.count(value) tells you how often a value occurs.', 'A baseline method can loop over every entry and count it when scores.count(value) > 1.', 'Start total = 0. In your loop, increase total only for entries meeting the rule. Print it after the loop.'],
    check: 'duplicates', goal: 'Print one integer. A blank input line represents an empty list and should give 0.',
    extension: 'Can you count frequencies once using a dictionary? Compare the work needed for a longer list.',
  },
  {
    id: 'gold', level: 'Gold', colour: 'gold', title: 'Find the target rectangles',
    summary: 'Explore a grid and count regions with the right total.', conceptsLabel: 'Nested loops · grids · decomposition', phase: 'Extend', time: 'Can continue next lesson',
    intro: 'A grid stores points. Count the rectangular regions whose cells add up to a target.',
    learn: 'A region uses consecutive rows and columns and contains at least one cell. Overlapping regions can both count. Start with a clear method on a tiny grid.',
    task: 'Read the number of rows and columns, then each row, then the target. Print the number of matching rectangles.',
    sample: [{input: '2 2\n1 1\n1 1\n2', output: '4'}, {input: '2 2\n1 2\n3 4\n3', output: '2'}],
    steps: ['Choose the top, bottom, left and right boundaries of a rectangle.', 'Add all cells inside those boundaries.', 'Count each rectangle whose sum equals the target.'],
    starter: 'rows, cols = map(int, input("Rows and columns: ").split())\ngrid = [list(map(int, input("Row: ").split())) for _ in range(rows)]\ntarget = int(input("Target: "))\n\n# Explore every non-empty rectangle and count matches.\n',
    hints: ['Write a helper to add the cells in one rectangle first.', 'For each top row, choose a bottom row at or below it. Do the same for left and right columns.', 'Include the bottom and right edges: range(top, bottom + 1) and range(left, right + 1).'],
    check: 'rectangles', goal: 'Print one integer. Checks use grids up to 3×3, including zeros and negative numbers.',
    extension: 'Once your baseline works, investigate a prefix-sum grid to calculate each rectangle sum more efficiently.',
  },
];

export const allTasks = [...lesson, ...challenges];
export const lessonPlan = [
  ['0–2', 'Welcome', 'Open the lesson. Keep ownership of your code.', 'Set expectations: try, test, explain; all levels open.'],
  ['2–7', 'Do now', 'Run and change the welcome message.', 'Observe starting confidence and resolve access problems.'],
  ['7–10', 'Types of learning', 'Identify knowledge, skills and understanding.', 'State the common input/output goal.'],
  ['10–14', 'Short model', 'Follow one input/output example.', 'Model Run, console input and a purposeful change.'],
  ['14–27', 'Main task 1', 'Work through cards and build a welcome.', 'Coach individuals and a small support group.'],
  ['27–31', 'Learning pit stop', 'Choose support, practice or extension.', 'Respond to the current need.'],
  ['31–53', 'Main task 2', 'Choose a scenario, build and test.', 'Ask pupils to explain their code and test choices.'],
  ['53–60', 'Plenary', 'Demonstrate, download and reflect.', 'Sample individual evidence and plan next steps.'],
];
